server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices_rating
    username: root
    password: Vikas@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: RATING-SERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka